server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://stats-server:6542/stats-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver